apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: mealie-data
      mountPath: /app/data
  volumes:
  - name: mealie-data
    persistentVolumeClaim:
      claimName: mealie-data
